/* eslint-disable @next/next/no-sync-scripts */
"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";
import AuthProvider, { AuthContext } from "@/contexts/AuthProvider";
import { useContext } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Main({ children }) {
  const {changeTheme} = useContext(AuthContext);
  return (
    <html lang="en" data-theme={changeTheme ? 'night' : 'light'}>
    <body className={inter.className}>
      <Nav />
      {children}
      <script src="//at.alicdn.com/t/c/font_4088173_fcyx9liuok.js"></script>
    </body>
  </html>
  )
}

export default function RootLayout({children}) {

  return (
    <AuthProvider>
     <Main>
      {children}
     </Main>
    </AuthProvider>
  );
}
